variables:
   DOC_ROOT: $(Build.SourcesDirectory)/ACE
   ACE_ROOT: $(Build.SourcesDirectory)/ACE/ACE
   MPC_ROOT: $(Build.SourcesDirectory)/ACE/MPC
   TAO_ROOT: $(Build.SourcesDirectory)/ACE/TAO
   RIDL_ROOT: $(Build.SourcesDirectory)/ridl
   TAOX11_BASE_ROOT: $(Build.SourcesDirectory)
   TAOX11_ROOT: $(Build.SourcesDirectory)/taox11
   CIAOX11_ROOT: $(Build.SourcesDirectory)/ciaox11
   DANCEX11_ROOT: $(Build.SourcesDirectory)/dancex11
   system.prefergit: true

resources:
- repo: self
  fetchDepth: 1

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-18.04
  strategy:
    matrix:
      GCC8:
        CC: gcc-8
        CXX: g++-8
        PackageDeps: g++-8
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.4'
      addToPath: true
    displayName: Install ruby
  - script: |
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ $(Repo) main"
    displayName: Add repository ($(Repo))
    condition: and(succeeded(), ne(variables['Repo'], ''))
  - script: |
      sudo apt-get --yes update
      sudo apt-get --yes install libxerces-c-dev libssl-dev $(PackageDeps)
    displayName: install system package dependencies
  - powershell: |
      git clone --depth 1 git://github.com/DOCGroup/ACE_TAO.git $(DOC_ROOT)
      git clone --depth 1 git://github.com/DOCGroup/MPC.git $(MPC_ROOT)
      git clone --depth 1 git://github.com/RemedyIT/ridl.git $(RIDL_ROOT)
      git clone --depth 1 git://github.com/RemedyIT/taox11.git $(TAOX11_ROOT)
      git clone --depth 1 git://github.com/RemedyIT/ciaox11.git $(CIAOX11_ROOT)
      git clone --depth 1 git://github.com/RemedyIT/dancex11.git $(DANCEX11_ROOT)
    displayName: git clone dependent repositories
  - powershell: |
      bin/brix11 -t gnuace -E configure -w workspace -b 64 -I $(CIAOX11_ROOT) -I $(DANCEX11_ROOT)
    displayName: Run brix11 configure
  - powershell: |
      bin/brix11 env
      bin/brix11 configure -w workspace -P
    displayName: Print brix11 configuration
  - powershell: |
      bin/brix11 gen build workspace.mwc
      bin/brix11 gen build $(TAOX11_ROOT)/examples -- gen build $(TAOX11_ROOT)/orbsvcs/tests -- gen build $(TAOX11_ROOT)/tests
      bin/brix11 gen build $(DANCEX11_ROOT)/tests
    displayName: Run brix11 gen build
  - powershell: |
      bin/brix11 make -N -d
      bin/brix11 make -N -d $(TAOX11_ROOT)/examples
      bin/brix11 make -N -d $(TAOX11_ROOT)/orbsvcs/tests
      bin/brix11 make -N -d $(TAOX11_ROOT)/tests
      bin/brix11 make -N -d $(DANCEX11_ROOT)/tests
      bin/brix11 make -N -d -L $(DOC_ROOT)/ciaox11=$(DOC_ROOT)/ciaox11/bin/ciaox11_tests.lst
    displayName: Run brix11 make
